apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: default
spec:
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: registry.skysolutions.fi/library/logoutput:latest@sha256:6fa1339f3ca63f82c7532750dc63f4a999489404bd6611a9f729d8aa320963da
