apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
  namespace: default
spec:
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: app
          image: registry.skysolutions.fi/library/project:latest@sha256:62f13c9a9ae099be7ae77c11f0b01f245fa3ec35f2ad97b16dfc45fa98f952ac
---
apiVersion: v1
kind: Service
metadata:
  name: project-svc
  namespace: default
spec:
  type: LoadBalancer # No support for NodePort in my on-prem Talos cluster
  selector:
    app: project
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 80
      targetPort: 5000